### ISSUE TITLE
Investigate a Windows XP compatible build

### ISSUE THREAD

**Issue by muellni** [FAForever/ice-adapter#45]
Use latest nodejs 5.x and chrome/webrtc 49.x

**Comment by duk3luk3** [comment]
So this has been pretty much thwarted by chromium moving from SVN to git at some point after chromium 49, so none of the commit hashes made sense, and once I actually found the correct commit to check out, it couldn't be built because all its dependencies pointed at old, no longer valid URLs.

Results / other facts:
* Terribly disappointed in Google
* Amount of work to get this to work assuming *no* further obstacles other than fixing all of the dependencies would be huge
* XP is deprecated, FAF does not officially support XP anyway
* Based on UAs hitting www.faforever.com, amount of FAF users using XP is ~2% (interestingly, amount of FAF users using Win 10 is 1.8%).

Conclusion:
No Windows XP support. RIP Windows XP.

Todo:
Communicate this to players, which I am sure our Player Councillor will be happy to do.
